# Generated by Django 5.2.17 on 2026-09-24 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='线路名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前生效线路')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '线路',
                'verbose_name_plural': '线路',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='点位编码')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='点位名称')),
                ('position', models.PositiveIntegerField(verbose_name='规定顺序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='domain.course', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '打卡点',
                'verbose_name_plural': '打卡点',
                'ordering': ['course', 'position'],
                'unique_together': {('course', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80, verbose_name='队名')),
                ('checkpoint_sequence', models.JSONField(default=list, verbose_name='提交的到点顺序')),
                ('total_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='总用时（秒）')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('finished', '完赛'), ('incomplete', '未完赛'), ('revoked', '已撤销')], default='pending', max_length=16, verbose_name='成绩状态')),
                ('issue_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='未完成/撤销原因')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='名次')),
                ('revoke_count', models.PositiveIntegerField(default=0, verbose_name='撤销次数')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='domain.course', verbose_name='线路')),
            ],
            options={
                'verbose_name': '队伍成绩',
                'verbose_name_plural': '队伍成绩',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['team_name', 'status'], name='domain_team_team_na_da422f_idx')],
            },
        ),
    ]
