# Generated by Django 5.1.4 on 2026-09-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='线路名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='线路说明')),
                ('checkpoint_sequence', models.JSONField(default=list, verbose_name='规定点位顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '线路',
                'verbose_name_plural': '线路',
                'db_table': 'route',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120, verbose_name='队名')),
                ('submitted_sequence', models.JSONField(default=list, verbose_name='提交到点顺序')),
                ('total_seconds', models.PositiveIntegerField(verbose_name='总用时（秒）')),
                ('status', models.CharField(choices=[('completed', '完成'), ('incomplete', '未完成'), ('revoked', '已撤销')], default='incomplete', max_length=16, verbose_name='成绩状态')),
                ('issues', models.JSONField(default=list, verbose_name='未完成原因')),
                ('result_note', models.CharField(blank=True, default='', max_length=255, verbose_name='成绩栏说明')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='提交完成时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='撤销原因')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='domain.route', verbose_name='线路')),
            ],
            options={
                'verbose_name': '队伍成绩',
                'verbose_name_plural': '队伍成绩',
                'db_table': 'team_result',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['route', 'status'], name='team_result_route_i_3267f2_idx'), models.Index(fields=['route', 'team_name'], name='team_result_route_i_615535_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'revoked'), _negated=True), fields=('route', 'team_name'), name='uniq_active_result_per_team_route')],
            },
        ),
    ]
